Consider about UpdateException in Update(), re-implement TryUpdate()
Implement a provision of problem in ObjectContextStorage.Update() about
UpdateException: Added-state entities which is already inserted by another
context (causes constraint violation).
Re-implement TryUpdate() method; originally in StorageModule, update only if
not locked, but now re-defined its function, in ObjectContextStorage, update
the context, and retry automatically if failed to save changes.